import 'package:flutter/widgets.dart';
import "package:quizui/screens/next/next_describe.dart";
import "package:quizui/screens/next/next_listening.dart";
import "package:quizui/screens/next/next_writing.dart";
import "package:quizui/screens/next/next_select.dart";
import "package:quizui/screens/next/next_gpt.dart";
import 'package:flutter/material.dart';

class Home extends StatefulWidget {
  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.fromLTRB(16, 40, 16, 32),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Improve your skills for the Duolingo English Test',
              style: TextStyle(
                fontSize: 22,
                fontWeight: FontWeight.bold,
                color: Colors.orange,
              ),
            ),
            SizedBox(height: 20),
            _buildCategoryTile(context, Icons.edit, Colors.green, 'Writing',
                'Describe an image', _onTapWriting),
            _buildDivider('Writing'),
            _buildCategoryTile(context, Icons.hearing, Colors.blue, 'Listening',
                'Type what you hear', _onTapListening),
            _buildDivider('Listening'),
            _buildCategoryTile(context, Icons.book, Colors.purple, 'Writing',
                'Answer the prompt', _onTapReading),
            _buildDivider('Reading'),
            _buildCategoryTile(
                context,
                Icons.library_books,
                Colors.red,
                'Vocabulary',
                'Select the real English words',
                _onTapVocabulary),
            _buildDivider('Vocabulary'),
            _buildCategoryTile(
                context,
                Icons.language,
                Colors.orange,
                'Twilio',
                'Check out the prompts and answers generated by our AI',
                _onTapDuolingo),
          ],
        ),
      ),
    );
  }

  Widget _buildCategoryTile(BuildContext context, IconData icon, Color color,
      String title, String subtitle, VoidCallback onTap) {
    return ListTile(
      leading: Icon(icon, color: color),
      title: Text(title),
      subtitle: Text(subtitle),
      onTap: onTap,
    );
  }

  Widget _buildDivider(String sectionName) {
    return Row(
      children: [
        Expanded(child: Divider()),
        SizedBox(width: 8),
        SizedBox(width: 8),
        Expanded(child: Divider()),
      ],
    );
  }

  void _onTapWriting() {
    Navigator.of(context)
        .push(MaterialPageRoute(builder: (context) => NextDescribe()));
  }

  void _onTapListening() {
    Navigator.of(context)
        .push(MaterialPageRoute(builder: (context) => NextListening()));
  }

  void _onTapReading() {
    Navigator.of(context)
        .push(MaterialPageRoute(builder: (context) => NextWriting()));
  }

  void _onTapVocabulary() {
    Navigator.of(context)
        .push(MaterialPageRoute(builder: (context) => NextSelect()));
  }

  void _onTapDuolingo() {
    Navigator.of(context)
        .push(MaterialPageRoute(builder: (context) => NextGpt()));
  }
}
